Repository berops/claudie, pull requests merged in 2023-06, with the labels that each got.

#806 Refactoring the ansibler microservice
  Makefile
  internal/templateUtils/templates.go
  internal/utils/api-endpoint.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  proto/ansibler.proto
  services/ansibler/server/adapters/inbound/grpc/adapter.go
  services/ansibler/server/adapters/inbound/grpc/ansibler_service.go
  services/ansibler/server/ansibler.go
  services/ansibler/server/api-endpoint.go
  services/ansibler/server/domain/usecases/install_node_requirements.go
  services/ansibler/server/domain/usecases/install_vpn.go
  services/ansibler/server/domain/usecases/setup_loadbalancers.go
  services/ansibler/server/domain/usecases/tear_down_loadbalancer.go
  services/ansibler/server/domain/usecases/update_api_endpoint.go
  services/ansibler/server/domain/usecases/usecases.go
  services/ansibler/server/loadbalancers.go
  services/ansibler/server/nodeRequirments.go
  services/ansibler/server/server.go
  services/ansibler/server/utils/ansible.go
  services/ansibler/server/utils/api-endpoint.go
  services/ansibler/server/utils/loadbalancers.go
  services/ansibler/server/vpn.go
  services/ansibler/templates/all-node-inventory.goini
  services/builder/intermediate_representation.go
  services/terraformer/Dockerfile
Labels: refactoring, go

#855 Improve docs about docs
  docs/docs-guides/deployment-workflow.md
  docs/docs-guides/development.md
Labels: documentation, enhancement

#868 Rework error saving in Scheduler
  manifests/claudie/kustomization.yaml
  services/scheduler/domain/usecases/config_processor.go
Labels: chore

#895 Update go modules
  go.mod
  go.sum
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
Labels: go

#901 Feature/crd autoscaler status
  .github/workflows/CI-pipeline.yml
  internal/envs/envs.go
  manifests/claudie/.env
  manifests/claudie/cluster-rbac/clusterrole.yaml
  manifests/claudie/cluster-rbac/clusterrolebinding.yaml
  manifests/claudie/cluster-rbac/kustomization.yaml
  manifests/claudie/frontend.yaml
  manifests/claudie/kuber.yaml
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  proto/config.proto
  proto/frontend.proto
  proto/pb/config.pb.go
  proto/pb/frontend.pb.go
  proto/pb/frontend_grpc.pb.go
  services/autoscaler-adapter/claudie_provider/claudie_node_groups.go
  services/autoscaler-adapter/claudie_provider/claudie_provider.go
  services/context-box/server/adapters/inbound/grpc/adapter.go
  services/context-box/server/adapters/outbound/mongodb_connector.go
  services/frontend/client/client.go
  services/frontend/client/client_test.go
  services/frontend/main.go
  services/frontend/pkg/controller/controller.go
  services/frontend/pkg/controller/controller_types.go
  services/frontend/server/adapters/inbound/grpc/adapter.go
  services/frontend/server/adapters/inbound/grpc/frontend_service.go
  services/frontend/server/adapters/outbound/context_box_connector.go
  services/frontend/server/domain/ports/context_box.go
  services/frontend/server/domain/usecases/process_manifest_files.go
  services/frontend/server/domain/usecases/send_autoscaler_event.go
  services/frontend/server/domain/usecases/usecases.go
  services/kuber/server/autoscaler/cluster_autoscaler.go
  services/kuber/templates/cluster-autoscaler.goyaml
  services/scheduler/domain/usecases/create_desired_state.go
Labels: bug
