Repository berops/claudie, pull requests merged in 2023-04, with the labels that each got.

#691 Feat/refactor probes
  go.mod
  go.sum
  internal/envs/envs.go
  internal/grpc-health-probe-Liveness/README.md
  internal/grpc-health-probe-Liveness/main.go
  internal/healthcheck/healthcheck.go
  internal/healthcheck/healthcheckServer.go
  manifests/claudie/ansibler.yaml
  manifests/claudie/context-box.yaml
  manifests/claudie/kube-eleven.yaml
  manifests/claudie/kuber.yaml
  manifests/claudie/kustomization.yaml
  manifests/claudie/terraformer.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/Dockerfile
  services/ansibler/server/server.go
  services/builder/builder.go
  services/context-box/Dockerfile
  services/context-box/server/server.go
  services/frontend/Dockerfile
  services/frontend/frontend.go
  services/frontend/server.go
  services/kube-eleven/Dockerfile
  services/kube-eleven/server/server.go
  services/kuber/Dockerfile
  services/kuber/server/server.go
  services/scheduler/scheduler.go
  services/terraformer/Dockerfile
  services/terraformer/server/server.go
Labels: enhancement, go

#709 Update provider version containing crucial fix
  internal/healthcheck/healthcheck.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/terraformer/templates/providers.tpl
Labels: bug

#701 Implementing clean architecture for the frontend microservice
  manifests/claudie/kustomization.yaml
  services/frontend/adapters/inbound/k8s_sidecar_notifications_receiver.adapter.go
  services/frontend/adapters/outbound/context_box_connector.adapter.go
  services/frontend/domain/ports/context_box.port.go
  services/frontend/domain/usecases/process_manifest_files.go
  services/frontend/domain/usecases/usecases.go
  services/frontend/domain/usecases/watch_configs.go
  services/frontend/frontend.go
  services/frontend/main.go
  services/frontend/process_configs.go
  services/frontend/server.go
  services/terraformer/server/terraform/terraform.go
Labels: refactoring, go

#717 Update dependabot dependencies
  go.mod
  go.sum
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
Labels: chore

#698 Feat/storage disk
  Makefile
  docs/config/config.md
  docs/input-manifest/example.yaml
  docs/input-manifest/input-manifest.md
  docs/input-manifest/providers/examples/aws-input-manifest.md
  docs/input-manifest/providers/examples/azure-input-manifest.md
  docs/input-manifest/providers/examples/gcp-input-manifest.md
  docs/input-manifest/providers/examples/hetzner-input-manifest.md
  docs/input-manifest/providers/examples/oci-input-manifest.md
  docs/storage/storage-solution.md
  internal/kubectl/kubectl.go
  internal/manifest/manifest.go
  internal/manifest/utils.go
  internal/manifest/validate_test.go
  manifests/claudie/dynamo/dynamodb.yaml
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  manifests/testing-framework/test-sets/autoscaling/1.yaml
  manifests/testing-framework/test-sets/autoscaling/2.yaml
  manifests/testing-framework/test-sets/autoscaling/3.yaml
  manifests/testing-framework/test-sets/test-set1/1.yaml
  manifests/testing-framework/test-sets/test-set1/2.yaml
  manifests/testing-framework/test-sets/test-set1/3.yaml
  manifests/testing-framework/test-sets/test-set2/1.yaml
  manifests/testing-framework/test-sets/test-set2/2.yaml
  manifests/testing-framework/test-sets/test-set2/3.yaml
  manifests/testing-framework/test-sets/test-set3/1.yaml
  manifests/testing-framework/test-sets/test-set3/2.yaml
  manifests/testing-framework/test-sets/test-set3/3.yaml
  manifests/testing-framework/test-sets/test-set3/4.yaml
  proto/config.proto
  proto/pb/config.pb.go
  services/autoscaler-adapter/node_manager/node_manager.go
  services/context-box/server/claudieDB/claudieMongo_test.go
  services/kube-eleven/server/addons/calico.yaml
  services/kuber/server/longhorn/longhorn.go
  services/kuber/server/manifests/claudie-defaults.yaml
  services/kuber/templates/storage-class.goyaml
  services/terraformer/client/client_test.go
  services/terraformer/server/clusterBuilder/clusterBuilder_test.go
  services/terraformer/server/terraformer_test.go
  services/terraformer/templates/aws-lb.tpl
  services/terraformer/templates/aws.tpl
  services/terraformer/templates/azure-lb.tpl
  services/terraformer/templates/azure.tpl
  services/terraformer/templates/gcp-lb.tpl
  services/terraformer/templates/gcp.tpl
  services/terraformer/templates/hetzner.tpl
  services/terraformer/templates/oci-lb.tpl
  services/terraformer/templates/oci.tpl
Labels: enhancement, go
