Repository berops/claudie, pull requests merged in 2023-07, with the labels that each got.

#920 Use utils.GetClusterID where possible
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/server/domain/usecases/install_node_requirements.go
  services/ansibler/server/domain/usecases/install_vpn.go
  services/ansibler/server/domain/usecases/setup_loadbalancers.go
  services/ansibler/server/domain/usecases/tear_down_loadbalancer.go
  services/ansibler/server/domain/usecases/update_api_endpoint.go
  services/kube-eleven/server/domain/utils/kube-eleven/kube_eleven.go
  services/kuber/server/autoscaler/cluster_autoscaler.go
  services/kuber/server/longhorn/longhorn.go
  services/kuber/server/nodes/delete.go
  services/kuber/server/nodes/patch.go
  services/kuber/server/scrapeConfig/scrapeConfig.go
  services/kuber/server/server.go
  services/terraformer/server/domain/utils/cluster-builder/cluster_builder.go
  services/terraformer/server/domain/utils/kubernetes/kubernetes.go
  services/terraformer/server/domain/utils/loadbalancer/loadbalancer.go
  services/testing-framework/test_autoscaler.go
  services/testing-framework/test_longhorn.go
Labels: chore

#938 Add doc about local testing
  Makefile
  docs/contributing/local-testing.md
Labels: documentation

#937 Update go version and go packages
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/Dockerfile
  services/autoscaler-adapter/Dockerfile
  services/builder/Dockerfile
  services/context-box/Dockerfile
  services/frontend/Dockerfile
  services/kube-eleven/Dockerfile
  services/kuber/Dockerfile
  services/scheduler/Dockerfile
  services/terraformer/Dockerfile
  services/testing-framework/Dockerfile
Labels: dependencies, chore

#902 Feat/hybrid cloud
  .github/workflows/CI-pipeline.yml
  docs/input-manifest/api-reference.md
  docs/input-manifest/example.md
  docs/input-manifest/providers/on-prem.md
  internal/kubectl/kubectl.go
  internal/manifest/manifest.go
  internal/manifest/utils.go
  internal/manifest/validate.go
  internal/utils/cluster.go
  internal/utils/key.go
  internal/utils/utils.go
  manifests/claudie/crd/claudie.io_inputmanifests.yaml
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  manifests/testing-framework/test-sets/test-set5/1.yaml
  manifests/testing-framework/test-sets/test-set5/2.yaml
  manifests/testing-framework/test-sets/test-set5/3.yaml
  manifests/testing-framework/testing-framework.yaml
  mkdocs.yml
  proto/pb/frontend_grpc.pb.go
  services/ansibler/server/ansible-playbooks/longhorn-req.yml
  services/ansibler/server/ansible-playbooks/wireguard.yml
  services/ansibler/server/ansible-playbooks/wireguard/tasks/configure.yml
  services/ansibler/server/ansible-playbooks/wireguard/templates/wg-dynamic.conf.j2
  services/ansibler/server/ansible-playbooks/wireguard/templates/wg-static.conf.j2
  services/ansibler/server/domain/usecases/install_node_requirements.go
  services/ansibler/server/domain/usecases/install_vpn.go
  services/ansibler/server/domain/usecases/setup_loadbalancers.go
  services/ansibler/server/domain/usecases/update_api_endpoint.go
  services/ansibler/server/utils/loadbalancers.go
  services/ansibler/templates/all-node-inventory.goini
  services/builder/configProcessor.go
  services/builder/utils.go
  services/frontend/pkg/api/v1beta1/inputmanifest_types.go
  services/frontend/pkg/controller/controler_helpers.go
  services/frontend/pkg/controller/controller.go
  services/frontend/pkg/controller/validator.go
  services/kube-eleven/server/domain/utils/kube-eleven/kube_eleven.go
  services/kube-eleven/server/domain/utils/kube-eleven/types.go
  services/kube-eleven/server/domain/utils/kube-eleven/utils.go
  services/kube-eleven/templates/kubeone.tpl
  services/kuber/server/longhorn/longhorn.go
  services/testing-framework/claudie_test.go
  services/testing-framework/inputmanifest.go
  services/testing-framework/test_autoscaler.go
Labels: feature

#944 Add changelog for `v0.4.1`
  docs/CHANGELOG/changelog-0.4.x.md
Labels: documentation

#876 Feat/labels taints
  docs/claudie-workflow/claudie-workflow.md
  docs/input-manifest/api-reference.md
  docs/input-manifest/example.md
  internal/manifest/manifest.go
  internal/manifest/utils.go
  internal/manifest/validate_node_pool.go
  internal/manifest/validate_test.go
  internal/nodes/metadata.go
  internal/utils/cluster.go
  internal/utils/cluster_view.go
  internal/utils/utils.go
  manifests/claudie/crd/claudie.io_inputmanifests.yaml
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  manifests/testing-framework/test-sets/test-set1/1.yaml
  manifests/testing-framework/test-sets/test-set1/2.yaml
  manifests/testing-framework/test-sets/test-set1/3.yaml
  proto/config.proto
  proto/kuber.proto
  proto/pb/config.pb.go
  proto/pb/kuber_grpc.pb.go
  services/autoscaler-adapter/claudie_provider/node_template.go
  services/autoscaler-adapter/node_manager/node_manager.go
  services/autoscaler-adapter/node_manager/utils.go
  services/claudie-operator/pkg/api/v1beta1/inputmanifest_helpers.go
  services/claudie-operator/pkg/api/v1beta1/inputmanifest_types.go
  services/claudie-operator/pkg/controller/controller.go
  services/claudie-operator/pkg/controller/controller_types.go
  services/kube-eleven/server/domain/utils/kube-eleven/types.go
  services/kube-eleven/templates/kubeone.tpl
  services/kuber/server/nodes/patch.go
  services/kuber/server/server.go
  services/terraformer/server/domain/utils/cluster-builder/cluster_builder.go
Labels: enhancement

#955 Feat/ref builder
  internal/utils/grpc.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  proto/kuber.proto
  proto/pb/kuber.pb.go
  proto/pb/kuber_grpc.pb.go
  services/builder/adapters/outbound/ansibler_connector.go
  services/builder/adapters/outbound/context_box_connector.go
  services/builder/adapters/outbound/kube_eleven_connector.go
  services/builder/adapters/outbound/kuber_connector.go
  services/builder/adapters/outbound/terraformer_connector.go
  services/builder/builder.go
  services/builder/configProcessor.go
  services/builder/domain/ports/ansibler_port.go
  services/builder/domain/ports/context_box_port.go
  services/builder/domain/ports/kube_eleven_port.go
  services/builder/domain/ports/kuber_port.go
  services/builder/domain/ports/terraformer_port.go
  services/builder/domain/usecases/ansibler_caller.go
  services/builder/domain/usecases/config_processor.go
  services/builder/domain/usecases/kube_eleven_caller.go
  services/builder/domain/usecases/kuber_caller.go
  services/builder/domain/usecases/terraformer_caller.go
  services/builder/domain/usecases/usecases.go
  services/builder/domain/usecases/utils/builder_ctx.go
  services/builder/domain/usecases/utils/intermediate_representation.go
  services/builder/domain/usecases/utils/utils.go
  services/builder/domain/usecases/workflow_helpers.go
  services/builder/main.go
  services/builder/serviceCaller.go
  services/builder/utils.go
  services/claudie-operator/main.go
  services/claudie-operator/server/adapters/outbound/context_box_connector.go
  services/claudie-operator/server/domain/ports/context_box_port.go
  services/context-box/server/main.go
  services/kuber/client/client.go
  services/kuber/server/adapters/inbound/grpc/kuber_service.go
  services/kuber/server/domain/usecases/patch_nodes.go
  services/scheduler/main.go
Labels: refactoring, go
