Repository berops/claudie, pull requests merged in 2023-02, with the labels that each got.

#543 Feat/node labels
  docs/storage/storage-solution.md
  manifests/claudie/kustomization.yaml
  services/kube-eleven/server/kube-eleven/kube-eleven.go
  services/kube-eleven/templates/kubeone.tpl
  services/kuber/server/longhorn/longhorn.go
  services/kuber/templates/storage-class.goyaml
Labels: enhancement

#556 feature: replace MD5 with Blake2b
  go.mod
  go.sum
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/context-box/server/checksum/checksum.go
  services/context-box/server/checksum/checksum_test.go
Labels: go

#562 Feat/update docs
  README.md
  SECURITY.md
  docs/claudie-workflow/claudie-diagram.jpg
  docs/claudie-workflow/claudie-workflow.md
  docs/config/config.md
  docs/contributing/contributing.md
  docs/crud/crud.md
  docs/input-manifest/example.yaml
  docs/input-manifest/input-manifest.md
  docs/input-manifest/providers/aws.md
  docs/input-manifest/providers/azure.md
  docs/input-manifest/providers/cloudflare.md
  docs/input-manifest/providers/examples/aws-input-manifest.md
  docs/input-manifest/providers/examples/azure-input-manifest.md
  docs/input-manifest/providers/examples/gcp-input-manifest.md
  docs/input-manifest/providers/examples/hetzner-input-manifest.md
  docs/input-manifest/providers/examples/oci-input-manifest.md
  docs/input-manifest/providers/gcp.md
  docs/input-manifest/providers/hetzner.md
  docs/input-manifest/providers/oci.md
  docs/loadbalancing/loadbalancing-solution.md
  docs/roadmap/roadmap.md
  docs/use-cases/use-cases.md
Labels: documentation, enhancement

#509 feat: add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#577 Chore/update deps
  go.mod
  go.sum
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/Dockerfile
Labels: dependencies

#578 Add Changelog for `v0.1.2`
  docs/CHANGELOG/changelog-0.1.x.md
Labels: documentation

#579 Feat/cloud labels
  internal/command/cmd.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/terraformer/templates/aws-dns.tpl
  services/terraformer/templates/aws-lb.tpl
  services/terraformer/templates/aws.tpl
  services/terraformer/templates/azure-dns.tpl
  services/terraformer/templates/azure-lb.tpl
  services/terraformer/templates/azure.tpl
  services/terraformer/templates/backend.tpl
  services/terraformer/templates/cloudflare-dns.tpl
  services/terraformer/templates/gcp-dns.tpl
  services/terraformer/templates/gcp-lb.tpl
  services/terraformer/templates/gcp.tpl
  services/terraformer/templates/hetzner-lb.tpl
  services/terraformer/templates/hetzner.tpl
  services/terraformer/templates/hetznerdns-dns.tpl
  services/terraformer/templates/oci-dns.tpl
  services/terraformer/templates/oci-lb.tpl
  services/terraformer/templates/oci.tpl
  services/terraformer/templates/providers.tpl
Labels: enhancement, dependencies, chore

#597 utils: extend the kubeconfig-sanitising regex+test
  internal/utils/log.go
  internal/utils/log_test.go
Labels: enhancement, go, security
