Repository berops/claudie, pull requests merged in 2023-05, with the labels that each got.

#773 Feat/deletion error
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/server/ansible/ansible.go
  services/builder/configProcessor.go
  services/builder/utils.go
  services/context-box/server/cbox.go
  services/context-box/server/claudieDB/claudieMongo.go
  services/context-box/server/server.go
  services/kuber/server/autoscaler/cluster_autoscaler.go
  services/kuber/server/longhorn/longhorn.go
  services/kuber/server/nodes/delete.go
  services/kuber/server/nodes/patch.go
  services/kuber/server/scrapeConfig/scrapeConfig.go
  services/kuber/server/secret/secret.go
  services/terraformer/server/terraform/terraform.go
  services/testing-framework/secret.go
  services/testing-framework/test_longhorn.go
Labels: bug

#785 Simplify Get started section
  README.md
  docs/crud/crud.md
Labels: documentation

#782 Feat/volume replication
  Makefile
  internal/kubectl/kubectl.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/kuber/server/nodes/delete.go
  services/kuber/server/nodes/pvc_replication_utils.go
  services/terraformer/templates/gcp.tpl
  services/testing-framework/utils.go
Labels: bug

#805 Feat/ca improvement
  .github/workflows/CI-pipeline.yml
  .github/workflows/release.yml
  Makefile
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/kuber/server/autoscaler/autoscaler_test.go
  services/kuber/server/autoscaler/cluster_autoscaler.go
  services/kuber/templates/autoscaler-adapter.goyaml
  services/kuber/templates/cluster-autoscaler.goyaml
Labels: enhancement

#819 Feat/go embed
  internal/templateUtils/templates.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/Dockerfile
  services/ansibler/server/ansibler.go
  services/ansibler/server/api-endpoint.go
  services/ansibler/server/loadbalancers.go
  services/ansibler/server/nodeRequirments.go
  services/ansibler/server/vpn.go
  services/ansibler/templates/node-exporter.goyml
  services/ansibler/templates/node-exporter.service.j2
  services/ansibler/templates/templates.go
  services/kube-eleven/Dockerfile
  services/kube-eleven/server/kube-eleven/kube-eleven.go
  services/kube-eleven/templates/templates.go
  services/kuber/Dockerfile
  services/kuber/server/autoscaler/autoscaler_test.go
  services/kuber/server/autoscaler/cluster_autoscaler.go
  services/kuber/server/longhorn/longhorn.go
  services/kuber/server/scrapeConfig/scrapeConfig.go
  services/kuber/templates/templates.go
  services/terraformer/server/backend/backend.go
  services/terraformer/server/clusterBuilder/clusterBuilder.go
  services/terraformer/server/clusterBuilder/clusterBuilder_test.go
  services/terraformer/server/loadbalancer/dns.go
  services/terraformer/server/provider/provider.go
  services/terraformer/templates/aws/dns.tpl
  services/terraformer/templates/aws/k8s.tpl
  services/terraformer/templates/aws/lb.tpl
  services/terraformer/templates/aws/provider-k8s.tpl
  services/terraformer/templates/aws/provider-lb.tpl
  services/terraformer/templates/azure/dns.tpl
  services/terraformer/templates/azure/k8s.tpl
  services/terraformer/templates/azure/lb.tpl
  services/terraformer/templates/azure/provider-k8s.tpl
  services/terraformer/templates/azure/provider-lb.tpl
  services/terraformer/templates/cloudflare/dns.tpl
  services/terraformer/templates/gcp/dns.tpl
  services/terraformer/templates/gcp/k8s.tpl
  services/terraformer/templates/gcp/lb.tpl
  services/terraformer/templates/gcp/provider-k8s.tpl
  services/terraformer/templates/gcp/provider-lb.tpl
  services/terraformer/templates/hetzner/k8s.tpl
  services/terraformer/templates/hetzner/lb.tpl
  services/terraformer/templates/hetzner/provider-k8s.tpl
  services/terraformer/templates/hetzner/provider-lb.tpl
  services/terraformer/templates/hetznerdns/dns.tpl
  services/terraformer/templates/oci/dns.tpl
  services/terraformer/templates/oci/k8s.tpl
  services/terraformer/templates/oci/lb.tpl
  services/terraformer/templates/oci/provider-k8s.tpl
  services/terraformer/templates/oci/provider-lb.tpl
  services/terraformer/templates/templates.go
  services/testing-framework/Dockerfile
  services/testing-framework/secret.go
  services/testing-framework/templates/templates.go
Labels: go

#786 Implementing clean architecture for the Terraformer microservice
  manifests/claudie/kustomization.yaml
  services/terraformer/server/adapters/inbound/grpc/adapter.go
  services/terraformer/server/adapters/inbound/grpc/terraformer_service.go
  services/terraformer/server/adapters/outbound/dynamodb_adapter.go
  services/terraformer/server/adapters/outbound/minio_adapter.go
  services/terraformer/server/domain/ports/dynamodb.go
  services/terraformer/server/domain/ports/minio.go
  services/terraformer/server/domain/usecases/build_infrastructure.go
  services/terraformer/server/domain/usecases/destroy_infrastructure.go
  services/terraformer/server/domain/usecases/usecases.go
  services/terraformer/server/domain/utils/backend/backend.go
  services/terraformer/server/domain/utils/cluster-builder/cluster_builder.go
  services/terraformer/server/domain/utils/cluster-builder/cluster_builder_test.go
  services/terraformer/server/domain/utils/kubernetes/kubernetes.go
  services/terraformer/server/domain/utils/loadbalancer/dns.go
  services/terraformer/server/domain/utils/loadbalancer/loadbalancer.go
  services/terraformer/server/domain/utils/provider/provider.go
  services/terraformer/server/domain/utils/terraform/terraform.go
  services/terraformer/server/domain/utils/terraform/terraform_test.go
  services/terraformer/server/kubernetes/kubernetes.go
  services/terraformer/server/loadbalancer/loadbalancer.go
  services/terraformer/server/main.go
  services/terraformer/server/server.go
  services/terraformer/server/terraformer_test.go
Labels: refactoring, go

#798 Refactoring kube-eleven microservice
  manifests/claudie/kustomization.yaml
  services/kube-eleven/server/adapters/inbound/grpc/adapter.go
  services/kube-eleven/server/adapters/inbound/grpc/kube_eleven_service.go
  services/kube-eleven/server/domain/usecases/build_cluster.go
  services/kube-eleven/server/domain/usecases/usecases.go
  services/kube-eleven/server/domain/utils/kube-eleven/kube_eleven.go
  services/kube-eleven/server/domain/utils/kube-eleven/types.go
  services/kube-eleven/server/domain/utils/kube-eleven/utils.go
  services/kube-eleven/server/domain/utils/kubeone/kubeone.go
  services/kube-eleven/server/kube-eleven/kube-eleven.go
  services/kube-eleven/server/main.go
  services/kube-eleven/server/server.go
  services/kube-eleven/server/server_test.go
  services/kube-eleven/templates/kubeone.tpl
Labels: refactoring, go
