Repository berops/claudie, pull requests merged in 2023-01, with the labels that each got.

#490 Feat/auto clean up
  .github/workflows/CD-pipeline-dev.yml
  .github/workflows/CI-pipeline.yml
  Makefile
  manifests/testing-framework/kustomization.yaml
  manifests/testing-framework/testing-framework.yaml
  services/testing-framework/claudie_test.go
  services/testing-framework/secret.go
Labels: enhancement

#474 Update kubernetes version validation & docs
  .github/workflows/CD-pipeline-dev.yml
  .github/workflows/CI-pipeline.yml
  .github/workflows/release.yml
  docs/input-manifest/input-manifest.md
  internal/manifest/validate_kubernetes.go
  internal/manifest/validate_test.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
Labels: go

#523 Feat/expon timeout
  internal/command/cmd.go
  internal/command/cmd_test.go
  internal/kubectl/kubectl.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
Labels: enhancement, go

#461 chore(docs): partially rewrite, fix typos
  README.md
  docs/claudie-workflow/claudie-workflow.md
  docs/config/config.md
  docs/contributing/contributing.md
  docs/crud/crud.md
  docs/input-manifest/input-manifest.md
  docs/loadbalancing/loadbalancing-solution.md
  docs/storage/storage-solution.md
Labels: documentation

#517 feat(dockerfiles): use $TARGETARCH everywhere
  Makefile
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/ansibler/Dockerfile
  services/builder/Dockerfile
  services/context-box/Dockerfile
  services/frontend/Dockerfile
  services/kube-eleven/Dockerfile
  services/kuber/Dockerfile
  services/scheduler/Dockerfile
  services/terraformer/Dockerfile
  services/testing-framework/Dockerfile
Labels: enhancement, docker

#506 feat: add a security policy file
  README.md
  SECURITY.md
Labels: enhancement, security

#531 Feat/changelog 0.1
  docs/CHANGELOG/changelog-0.1.x.md
Labels: documentation

#532 add anti-scraping features for contact email
  SECURITY.md
Labels: enhancement, security

#538 bugfix: sort out ansible failing to install WG due to unattended upgrades
  manifests/claudie/kustomization.yaml
  services/ansibler/server/ansible-playbooks/wireguard/tasks/configure.yml
  services/ansibler/server/ansible-playbooks/wireguard/tasks/install.yml
  services/ansibler/server/ansible-playbooks/wireguard/tasks/kill_unattended_upgrades.yml
  services/ansibler/server/ansible-playbooks/wireguard/tasks/main.yml
Labels: bug

#535 bugfix: sanitise log/console secrets
  internal/command/cmd.go
  internal/command/cmd_test.go
  internal/utils/log.go
  internal/utils/log_test.go
  manifests/claudie/kustomization.yaml
  manifests/testing-framework/kustomization.yaml
  services/context-box/server/claudieDB/claudieMongo.go
  services/context-box/server/server.go
Labels: bug, go, security

#536 Fix inequality of states after Claudie workflow
  manifests/claudie/kustomization.yaml
  services/context-box/server/server.go
Labels: bug
